version: '3.7'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: postgres
        PASSWORD: postgres
        DATABASE: scaleflix
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
      args:
        USER: postgres
        PASSWORD: postgres
        DATABASE: scaleflix
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: scaleflix
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  default:
volumes:
  data: